# Generated by Django 4.2.10 on 2024-02-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.TextField()),
                ('client_ip', models.CharField(max_length=100)),
                ('accept', models.TextField()),
                ('accept_encoding', models.TextField()),
                ('accept_language', models.TextField()),
                ('connection', models.TextField()),
                ('host', models.CharField(max_length=100)),
                ('referer', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('successful_login', models.BooleanField(default=False)),
            ],
        ),
    ]
